OnTheGoSystems/wpml-config

config-index.xml
subscriptio/wpml-config.xml

Reported in https://wpml.org/forums/topic/some-words-from-wc-subscriptio-plugin-are-displayed-only-in-default-language/

Required for subscriptio plugin

---

enfold/wpml-config.xml

[Enfold] Update xlm config file

---

divi-builder/wpml-config.xml
divi/wpml-config.xml
enfold/wpml-config.xml
extra/wpml-config.xml
x/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-2839

Adding type link to urls

---

config-index.xml
the-events-calendar/wpml-config.xml

- Added a few missing fields
- Change URL fields to translatable
- Fix formatting
To be used together with https://github.com/moderntribe/the-events-calendar/pull/1908

Changes required for The Events Calendar multilingual workflow

---

config-index.xml
custom-post-type-ui/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-2929

Custom Post Type UI

---

config-index.xml
js_composer-dt-the7/wpml-config.xml
uncode-js_composer/wpml-config.xml

Changed item ID and added separate files for Visual Composer forks.

Updated Visual Composer forks

---

divi-builder/wpml-config.xml
divi/wpml-config.xml

Updated config files for Divi products.

Update "Email Optin" module keys

---

the-events-calendar/wpml-config.xml

The author requested adding support to translated time and date formats

Add TEC admin texts

---

avada/wpml-config.xml
woocommerce-multilingual/wpml-config.xml

for wcml -> https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-2461

updating avada and wcml

---

cornerstone/wpml-config.xml
pro/wpml-config.xml
x/wpml-config.xml

Cleanup, removed non-text shortcodes (attributes), synced for X, Pro and Cornerstone.

Cleanup - removed non-text items

---

config-index.xml
exit-popup/wpml-config.xml

https://wordpress.org/plugins/exit-popup/

Add admin-texts for Exit Popup

---

enfold/wpml-config.xml

Setting these custom fields to `copy-once`
sidebar
footer
header_title_bar
header_transparency

setting Enfold custom fields

---

enfold/wpml-config.xml

missed the `layout` custom field

missing Enfold custom field

---

avada/wpml-config.xml

Requested here https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5375#comment=102-293116

Adding Fusion Element post type to Avada config file

---

avada/wpml-config.xml
cornerstone/wpml-config.xml
divi-builder/wpml-config.xml
divi/wpml-config.xml
dt-the7/wpml-config.xml
enfold/wpml-config.xml
extra/wpml-config.xml
js_composer-dt-the7/wpml-config.xml
js_composer/wpml-config.xml
uncode-js_composer/wpml-config.xml
uncode/wpml-config.xml
x/wpml-config.xml

As requested in comp-3075
Changes have been done for all page builders

comp-3075- Built with Page Builder

---

enfold/wpml-config.xml
js_composer-dt-the7/wpml-config.xml
js_composer/wpml-config.xml
uncode-js_composer/wpml-config.xml

This is the second round of cleaning. In the beginning, I was searching only for CSS stuff. Now, I've deleted links and code shortcodes.

Cleaning Enfold config file

---

wordpress-seo-premium/wpml-config.xml
wordpress-seo/wpml-config.xml

Issues from
https://github.com/Yoast/wordpress-seo/issues/9367
https://github.com/Yoast/wordpress-seo/issues/5060

Fixing Yoast and Yoast premium config files: issues 9367 and 5060

---

config-index.xml
sitepress-multilingual-cms/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5668

[for 4.1.0] Add wpml-config.xml for WPML core to easily add gutenberg blocks

---

divi-builder/wpml-config.xml
divi/wpml-config.xml
extra/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5819

[for 4.1.0] Add config for media shortcodes in Divi

---

avada/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5855

[for 4.1.0] Add media config for shortcodes in Fusion Builder (Avada)

---

enfold/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5860

[for 4.1.0] Add config for media shortcodes in Enfold

---

js_composer-dt-the7/wpml-config.xml
js_composer/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5859

[for 4.1.0] Add config for media shortcodes in WPBakery Page Builder

---

config-index.xml
forminator/wpml-config.xml

@comp-code-review please review and add

wpml-config file for Forminator plugin

---

woocommerce-name-your-price/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3155

Woocommerce Name Your Price - update xml file

---

enfold/wpml-config.xml

Reported here https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-3539

Adding section tab shortcode to the config file

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml
extra/wpml-config.xml

Adding missing attributes for Slide element

---

avada/wpml-config.xml

compsupp-3701- Setting fusion_slider_options to 'copy'

---

avada/wpml-config.xml

Please refer to https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-6566

Things work proper when element_category is not translatable.

---

config-index.xml
luster/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6765

Luster theme does not show properties for translated agent.

---

.gitignore
js_composer-dt-the7/wpml-config.xml
js_composer/wpml-config.xml
uncode-js_composer/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-6746

Translating column links

---

Divi/wpml-config.xml

This is needed for anchor links.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-4306

Translating the section CSS ID

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6738

Set _element_data to 'copy-once' for duplicates to work.

---

Divi/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6136

[Divi] Copy selective sync options to translations.

---

enfold/wpml-config.xml

Testing Enfold 4.6.4 and some custom fields need to have specific translation preferences.

Update Enfold custom fields

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml
extra/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6828

Add a few missing fields required for the Divi product builder

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml
extra/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-4482

Adding support for translating Blurb Module image

---

config-index.xml
woocommerce-mix-and-match-products/wpml-config.xml

The plugin author created this issue https://github.com/OnTheGoSystems/wpml-config/issues/107 and I'm adding the config file on our repository.

Adding xml config file for WooCommerce Mix and Match

---

Divi/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6888

Handle Divi theme builder header/body/footer layouts

---

uncode-js_composer/wpml-config.xml

Corrected vc_button link and added link attribute for vc_single_image.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-4058

Uncode - corrected vc_button and vc_single_image

---

wordpress-seo-premium/wpml-config.xml
wordpress-seo/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-7487

[WordPress SEO] Allow translating _yoast_wpseo_focuskeywords

---

avada/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3433

Adjust our wpml-config.xml to the latest wpml-config.xml supplied with Avada theme.

---

atomic-blocks/wpml-config.xml
config-index.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6627

Add config file for Atomic Blocks.

---

woocommerce-memberships/wpml-config.xml

Granting free memberships results in multiple memberships, each in every site language.
https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-3140

[COMPATIBILITY] WooCommerce Membership plugin (by SkyVerge)

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7080

Translate background image for  Divi columns

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5244

Handle translation of divi options.

---

config-index.xml
generatepress/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3454

GeneratePress - Copy hidden title setting

---

config-index.xml
ultimate-addons-for-gutenberg/wpml-config.xml

https://wordpress.org/plugins/ultimate-addons-for-gutenberg/

Add Ultimate Addons for Gutenberg config

---

generatepress/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/refsites-821

Setting custom fields to copy for the ref sites

---

js_composer/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-7884

Copying shortcodes custom CSS to the translation

---

bold-page-builder/wpml-config.xml

Just basic shortcodes that are most important (for me)
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3456

Basic shortcode support for Bold Page Builder

---

wordpress-seo-premium/wpml-config.xml
wordpress-seo/wpml-config.xml

[wordpress-seo] Add breadcrumb title to admin-texts

---

avada/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-7907

Update Avada fusion_map Element

---

wordpress-seo-premium/wpml-config.xml
wordpress-seo/wpml-config.xml

The term_id is auto-adjusted by WPML.

Copy primary category to translations.

---

sitepress-multilingual-cms/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7294

Add support for image block's title translation

---

enfold/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5025

Removing the encoding for Avia team member link

---

bold-page-builder/wpml-config.xml

Added translation functionality for bt_tabs_items and bt_text.

Added bt_tabs_items and bt_text

---

sitepress-multilingual-cms/wpml-config.xml

closes https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7341

Fixes flatsome translations.

---

advanced-gutenberg/wpml-config.xml
config-index.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/WPMLCC-1315

Add Advanced Gutenberg plugin config

---

avada/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5093

Select sub-keys from _fusion custom field for translation

---

enfold/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7375

For to translate the `core/shortcode` block in Enfold's Avia builder

---

sitepress-multilingual-cms/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7413

Adding configuration of xpath to translate table captions in GB

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5084

Adding support for Shortcode widget

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7701

Transpose Elementor's `form` widget config and make `field_html` an `AREA`

---

Divi/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5361

Add support for translating video background for Divi shortcodes

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3533

Make the landing pages translatable (for Elementor v3.1 currently in beta 2)

---

avada/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5443

Correct encoding for fusion_tagline_box::title

---

elementor/wpml-config.xml

https://github.com/OnTheGoSystems/wpml-config/compare/wpmlcore-7714

Elementor: translate the add-to-cart button label

---

astra/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3538

Add new admin strings for Astra 3.0

---

.gitignore
bin/update.php

Themes was missing, we were only validation plugin paths

Validate paths for themes and plugins

---

bin/validate
composer.json
composer.lock

@strategio Do you think we can use this in a github workflow?
Please review if you agree

Validate XML file when running composer

---

uncode/wpml-config.xml

`_uncode_secondary_thumbnail_id` added to config

Add support for new custom field

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5494

Add support for Recent Posts widget in Elementor

---

Divi/wpml-config.xml

Add redirect url in contact form

---

enfold/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3571

Allow HTML Tags in Enfold's icon box

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5244

Elementor - translate Video link in Media Carousel

---

enfold/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3508

Enfold - Set ALB Custom Elements  to be translated

---

cornerstone/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3596

[Cornerstone] transpose the shortcode config to the widget API config.

---

elementor/wpml-config.xml

This is for the default "WP Text" widget

Elementor - Add support for WP Text Widget

---

Divi/wpml-config.xml

We are adding the possibility of translatin the hover text for Divi text modules

compsupp-5587 - Text Hover content

---

enfold/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5590

Enfold - Translate Magazine block heading link

---

avada/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3608

Avada - Add support for Woo Cart Table shortcode

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5626

Added support for shortcode `et_pb_wc_add_to_cart`

---

Divi/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-2506

Divi - Translate section's background images

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3601

Add Elementor's "text path" widget

---

Divi/wpml-config.xml

Added "background_image_tablet" and "background_image_phone" support

Updates on "et_pb_slide"

---

config-index.xml
popup-maker/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3633

Popup Maker: prepare wpml-config.xml file

---

pro/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3606

PRO theme - Add support for Mega Menu sync

---

cornerstone/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3606

Cornerstone - Add support for Mega Menu sync

---

sensei/wpml-config.xml

- set question-type taxonomy as not transatable
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3380

Sensei: translated answers to quizz questions lost

---

.gitignore
composer.json
config-index.xml
siteorigin/wpml-config.xml
so-widgets-bundle/wpml-config.xml
wpml-config.xsd

Started off with the standard WordPress widgets and a few premium ones to cover the different use cases.
The parent merge request is: https://git.onthegosystems.com/glue-plugins/wpml/wpml-page-builders/-/merge_requests/3
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3498

Configuration file for SiteOrigin page builder integration

---

elementor/wpml-config.xml

Added mapping to media carousel's image URL

---

woocommerce-multilingual/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-2702

Set WC category images to be copied

---

config-index.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3667

Name change

---

cornerstone/wpml-config.xml
pro/wpml-config.xml
x/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3661

Review cornerstone configuration

---

config-index.xml
contact-form-7-multilingual/wpml-config.xml

The fist commit is just to copy the existing local config and make it the source of truth.

Exclude CF7 from "Translate Everything"

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml
extra/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7571

Allow HTML tags in description

---

astra/wpml-config.xml

This is for Astra 3.5
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3677

Astra - support translating Related Posts title

---

js_composer/wpml-config.xml
uncode-js_composer/wpml-config.xml

Replaces https://github.com/OnTheGoSystems/wpml-config/pull/213.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5684

[Uncode] Icon box and Recommendation widgets

---

elementor/wpml-config.xml

Replaces https://github.com/OnTheGoSystems/wpml-config/pull/213.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5706

[Elementor] adding Elementor start rating title

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3681

[Elementor] Add support for "Video Playlist" and "Hotspot" widgets

---

woocommerce-multilingual/wpml-config.xml
wpml-config.xsd

https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-3650

Exclude `product_variation` from "Translate Everything" mode

---

siteorigin/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-200

SiteOrigin: Add marker position info

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5735

Elementor PRO - Translate MailChimp tags

---

js_composer-dt-the7/wpml-config.xml
js_composer/wpml-config.xml
uncode-js_composer/wpml-config.xml

Added "link" attribute for the "vc_single_image" shortcode (compsupp-5753)
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5753

Updated vc_single_image shortcode

---

woocommerce-bookings/wpml-config.xml

Adds `_wc_booking_has_restricted_days` and `_wc_booking_has_restricted_days` set to copy.
Fix indentation in previous fields.

Add restricted day fields set to copy in bookings

---

elementor/wpml-config.xml

Added "link" for Image Carousel, Elementor widget (compsupp-5761)

compsupp-5761: adding Elementor - Image Carousel Custom link

---

ultimate-addons-for-gutenberg/wpml-config.xml

Includes the submit button from the form block to translate.
Includes the tab headers from the tabs block to translate.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5749

Add submit button and tab headers

---

avada/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3556

[DONT MERGE] Add support for Avada Forms shortcodes

---

elementor/wpml-config.xml

Adding Previous and Next button labels for the Form widget

compsupp-5857: Elementor Pro - Form widget

---

Divi/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5874
We need it so the style applied to the original is applied to the translation. There are no attributes to translate.

Adds et_pb_menu shortcode

---

avada/wpml-config.xml

[Avada] Copy to translations term meta for sliders

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml
extra/wpml-config.xml

Added link_option_url attr to et_pb_cta shortcode

Divi - et_pb_cta update

---

beaver-builder/wpml-config.xml

- Adding support for translation of modules: icon group and pricing table.
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3685

Testing Beaver Builder 2.5 alpha

---

elementor/wpml-config.xml

This new widget is introduced in Elementor's Pro v3.6.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-236

Add support for Elementor's WC Purchase Summary Widget

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-220

[Elementor] Add more `wp-widget-` widgets

---

config-index.xml
woocommerce-gift-cards/wpml-config.xml

Config for the e-mail strings for WooCommerce Gift Cards plugin https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6072

Config for WooCommerce Gift Cards

---

enfold/wpml-config.xml

- Add support to translate the select field options available when using the Contact module

Add support to translate Enfold select field options

---

avada/wpml-config.xml

[Avada] Added support for "fusion_form_text" and "fusion_form_phone_number" shortcodes

[Avada] Added support for some form fields

---

avada/wpml-config.xml

-  Adding the possibility to translate the title and title images coming from fusion_imageframe widget

[Avada] Added support for some fields of fusion_imageframe widget

---

avada/wpml-config.xml

Added the "preview_image" attribute to the "fusion_video" shortcode

compsupp-6160 - updated fusion_video shortcode

---

js_composer-dt-the7/wpml-config.xml

Fixing the issue in the js_composer-dt-the7 file

compsupp-6193 - fixed issue with vc_button shortcode

---

js_composer/wpml-config.xml

Fixed the issue with the vc_button shortcode

compsupp-6193 - fix issue with vc_button in the main js_composer file

---

click-to-chat-for-whatsapp/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/WPMLCC-1901

Changes in settings for click-to-chat-for-whatsapp

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3789

[Elementor] Add `stripe-button` widget

---

sitepress-multilingual-cms/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldev-424

[wpmldev-424] Adding core/navigation-submenu to sitepress plugin config

---

elementor/wpml-config.xml

Updated support for hotspot widget (compsupp-6303)

---

wordpress-seo-premium/wpml-config.xml
wordpress-seo/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlwpseo-162

Copy product primary category to translations

---

dt-the7/wpml-config.xml

This is the latest `wpml-config.xml` file for The7 v.10.11.0 theme.

Update The7 wpml-config.xml

---

activecampaign-subscription-forms/wpml-config.xml
config-index.xml
fluent-crm/wpml-config.xml
leadin/wpml-config.xml

Added XML configuration for the following plugins:
- ActiveCampaign: https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6335/Testing-ActiveCampaign-Forms-Site-Tracking-Live-Chat
- Hubspot: https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6067/Testing-HubSpot-CRM-Email-Marketing-Live-Chat-Forms-Analytics
- FluentCRM: https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6336/Testing-FluentCRM

Added XML for CRM plugins

---

bloom/wpml-config.xml
config-index.xml

Add XML config for the Bloom plugin

---

bloom/wpml-config.xml

Added support for shortcodes from the Bloom plugin

---

Divi/wpml-config.xml
divi-builder/wpml-config.xml
wpml-config.xsd

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-275

[Merge for WPML 4.6] Add support for Divi widgets referencing product ids

---

config-index.xml
optinmonster/wpml-config.xml

See https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6331
It's ready for publish/deploy

compsupp-6331 - Added OptinMonster settings

---

bloom/wpml-config.xml

- Adding support for excluding and including posts.
- Removing email_list list.
Reference:
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6339/Testing-Bloom-Elegant-Themes

Adding support for excluding and including posts

---

optinmonster/wpml-config.xml

(OptinMonster) Added support for the campaign-selector block

---

Divi/wpml-config.xml

(Divi) Adding support for "image__hover" on the et_pb_blurb shortcode.
See compsupp-6441

[Divi] - updated et_pb_blurb shortcode

---

js_composer-dt-the7/wpml-config.xml
js_composer/wpml-config.xml
uncode-js_composer/wpml-config.xml

Updated vc_single_image code on js_composer

---

dt-the7/wpml-config.xml

**Replaces https://github.com/OnTheGoSystems/wpml-config/pull/285**

WPML config for dt-the7 10.12.0

---

config-index.xml
edd-multilingual/wpml-config.xml
wpml-config.xsd

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlbridge-262/

[EDD] Add definition for buy-button block

---

woocommerce-memberships/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-3755/

[WooCommerce Membership] Copy subscription start/end dates 

---

Divi/wpml-config.xml

(Divi) Updated et_pb_menu shortcode

---

avada/wpml-config.xml

(Avada) Added support for "_fusion_google_fonts" field

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3840/

[comp-3840] Elementor 3.10 - Add nested tabs and countdown widgets config

---

avada/wpml-config.xml

[compsupp-6563] Avada - fusion_title shortcode

---

config-index.xml
hummingbird-performance/wpml-config.xml

See compsupp-6626
This issue is affecting ATE, so I set override_local="true"

Added config for Hummingbird

---

enfold/wpml-config.xml

[Enfold] Add support for av_icon_circle_item

---

elementor/wpml-config.xml

Making the Price field translatable for Price list widget
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6636

[Elementor] Translate "price" from Price list widget

---

kadence-blocks/wpml-config.xml

[Kadence blocks] 
- Add support for Button block - compsupp-6680
- Add support for the new Testimonial block - compsupp-6685

[Kadence blocks] - Add support for Button and Testimonial

---

siteorigin/wpml-config.xml

YT Ticket: https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-321

[WPMLPB-321] Force ignoring panels_data custom field

---

elementor/wpml-config.xml

YT Ticket: https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-111

Add support for elementor mega menu widget translation

---

sitepress-multilingual-cms/wpml-config.xml

feat: make the excerpt block link translatable

---

config-index.xml

Config not loaded for stackable premium

---

kadence-blocks/wpml-config.xml

[Kadence blocks] 
- Add support for Forms radio options 
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6868

[Kadence blocks] - Add support for Forms radio options

---

sitepress-multilingual-cms/wpml-config.xml

See https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldev-1309

Added config for wp_theme in sitepress-multilingual-cms

---

astra/wpml-config.xml

See [tsclientssupp-50](https://onthegosystems.myjetbrains.com/youtrack/issue/tsclientssupp-50)
- Part of this config was included in their local XML file: https://themes.trac.wordpress.org/browser/astra/4.1.6/wpml-config.xml 
- The other part was found by Sumit on tsclientssupp-50

Updated Astra XML config

---

the-events-calendar/wpml-config.xml

New taxonomies for organizers and venues.
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3903/Test-The-Events-Calendar-6.1.4

Prepare for The Events Calendar 6.1.4

---

stackable-ultimate-gutenberg-blocks/wpml-config.xml

Replacing https://github.com/OnTheGoSystems/wpml-config/pull/331 (@bfintal FYI)

[Stackable] Added config for timeline, tabs blocks and button link

---

kadence-blocks/wpml-config.xml

[Kadence Blocks] Updated infobox

---

Divi/wpml-config.xml

[Divi] added et_pb_icon

---

stackable-ultimate-gutenberg-blocks/wpml-config.xml

fixes https://github.com/gambitph/Stackable/issues/2511

[Stackable] Disable translations for the Map block

---

woocommerce-multilingual/wpml-config.xml

Added woocommerce_email_header_image to the WCML config file

---

elementor/wpml-config.xml

- Adding support for Elementor's Pro PayPal button 
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7042/Elementor-Pro-PayPal-button-widget-support

Adding support for Elementor's Pro PayPal button

---

js_composer-dt-the7/wpml-config.xml
js_composer/wpml-config.xml
uncode-js_composer/wpml-config.xml

Updated js_composer with icon and pricing table links

---

avada/wpml-config.xml

Updated Avada postcard shortcode

---

config-index.xml
woocommerce-product-add-ons/wpml-config.xml
woocommerce-product-addons/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-325/Rename-Woo-Product-Add-Ons-in-remote-wpml-config-repo

Rename Woo Product Add-Ons keeping backward compatibility

---

avada/wpml-config.xml

See compsupp-7155 for more details

Avada: Updated fusion_image tag

---

wordpress-seo-premium/wpml-config.xml
wordpress-seo/wpml-config.xml

Allowing to translate new custom fields added by Yoast 22.0.
- Organization description.
- Alternate organization name
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3932

Added support for Yoast 22.0 - Organization schema

---

astra/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-346/

[compdev-346] Astra: Add post layout settings to copy

---

kadence-blocks/wpml-config.xml

Adding support for Image (Adv) Block
- Translating images.
- Translating dynamic Alt texts
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7208/

Kadence - Adding support for Image (Adv) Block

---

Divi/wpml-config.xml

- Adding support for CTA (et_pb_cta) module new fields https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7220/Update-CTA-module-for-Divi-in-github

Divi - Added support for CTA (et_pb_cta ) new fields

---

js_composer-dt-the7/wpml-config.xml
js_composer/wpml-config.xml
uncode-js_composer/wpml-config.xml

WPBakery - Adding support for SEO feature
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7221

WPBakery - Adding support for SEO feature

---

avada/wpml-config.xml

- Making the Consent form field translatable in ATE
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7225

Avada - Added support for Consent Form Field

---

elementor/wpml-config.xml

- Adding support for Lottie File translation, caption and links
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7263

[Elementor] Adding support for Lottie File translation

---

avada/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-458/ATE-Layout-Add-URL-to-Avada-images

[wpmlpb-458] Set ATE labels for Avada image modules

---

sitepress-multilingual-cms/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-480

[wpmlpb-480] Allow translating core-social links in WPML

---

config-index.xml

- Adding Spectra (old Ultimate Addons for Gutenberg) to config.index.ml file https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7376

Adding Spectra plugin to config.index.ml file

---

ultimate-addons-for-gutenberg/wpml-config.xml

- Infobox: adding more robust support for translating the title.
- Button: making link translatable
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7376 https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7380

[Spectra] Adding support for Infobox and Buttons blocks

---

sitepress-multilingual-cms/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldev-2884/

[wpmldev-2884] Sync core changes to remote XML

---

config-index.xml

- Deleting kadence-blocks entry in the config-index.xml file https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7019

Deleting kadence-blocks XML file

---

Divi/wpml-config.xml

- [Divi] Related products module: adding support for included categories
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7342

Divi - Adding support for Related products module

---

pro/wpml-config.xml

In wpmlpb-283, we've made some modifications to the Cornerstone XML to add support for classic widgets.
The PRO theme has Cornerstone bundled, so we also need to update its XML.
See compsupp-7412 for more details

Updated PRO theme settings

---

ultimate-addons-for-gutenberg/wpml-config.xml

Updated configs for Spectra

---

cornerstone/wpml-config.xml
pro/wpml-config.xml

- Adding support for new buttons: allowing to translate label and. link
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7433/

[compsupp-7433] Cornerstone - Adding support for new buttons

---

ultimate-addons-for-gutenberg/wpml-config.xml

- Adding support for new FAQ blocks format
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7435/

[Spectra] Adding support for new FAQ blocks format

---

sitepress-multilingual-cms/wpml-config.xml

- Adding support for translating Footnotes block
- https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-510

[wpmlpb-510] Adding support for translating Footnotes block

---

elementor/wpml-config.xml

Register the new floating buttons CPT, and contact-buttons widget.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-519

[wpmlpb-519] Translate Floating Buttons.

---

wordpress-seo-premium/wpml-config.xml
wordpress-seo/wpml-config.xml

- Adding support for multiple entries of Related keyphrases: Keyphrase and Synonyms.
-https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7515

[Yoast] Adding support for multiple entries of Related keyphrases

---

woocommerce-multilingual/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-4802/

[wcml-4802] Add support to the `_global_unique_id` field in WC 9.2

---

avada/wpml-config.xml

- Added support for translating Circles info widgets
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7530/Avada-Circle-Info-Widget-not-translatable

[Avada] - Added support for translating Circles info widgets

---

elementor/wpml-config.xml

See https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7594

Updating Elementor XML - compsupp-7594

---

config-index.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/acfml-951

[acfml-951] Add Secure Custom Fields

---

dt-the7/wpml-config.xml

Update wpml-config.xml for The7 12.0.0

---

elementor/wpml-config.xml

- Making the Price field translatable for Price list widget
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6636

[Elementor Pro] Translate "price" field from Price list widget

---

cornerstone/wpml-config.xml

See https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-376/Cornerstone-Translate-nested-items#focus=Change-102-680423.0-0

Added support for Button > anchor_text_secondary_content (wpmlpb-376)

---

cornerstone/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-491/

[wpmlpb-491] Add support for image alt texts

---

elementor/wpml-config.xml
wpml-config.xsd

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-414

[wpmlpb-414] Transpose hardcoded configuration from WPML_Elementor_Translate_IDs

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-739/

[compdev-739] Fully transpose image and icon configuration to XML

---

wpml-config.xsd

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldev-4471/

[compdev-4471] Update `wpml-config.xsd` from WPML 4.7.3

---

bin/update.php
config-index.xml
global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldev-4694/

[wpmldev-4694] Introduce the `global` index and the `global-wpml-notices` XML config

---

global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-560

[compdev-560] Add remote notice for LearnDash on the TM Dashboard

---

seo-by-rank-math/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlwpseo-295

[wpmlwpseo-295] Rank Math SEO: Support term meta translation

---

Divi/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3831

[comp-3831] Divi 5 - New Blocks XML

---

global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-762

[compdev-762] Add remote notice for WPResidence on the TM Dashboard

---

global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-765

[compdev-765] Add a remote notice for JetEngine on the TM Dashboard

---

global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-764

[compdev-764] Add remote notice for Events Manager on the TM Dashboard and main events admin page

---

global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-760

[compdev-760] Add a remote notice for Formidable Forms on the TM Dashboard

---

config-index.xml
hello-plus/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-4038

[comp-4038] Added config for the Hello Plus addon (Elementor)

---

global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-778

[compdev-778] Add a remote notice for Oxygen Builder on the TM Dashboard

---

global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-777

[compdev-777] Add a remote notice for Breakdance on the TM Dashboard

---

global-wpml-notices/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/compdev-778

[compdev-778] Remote Notice: Fix Oxygen Builder notice ID

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-646

[wpmlpb-646] Fix image and icon links

---

ultimate-addons-for-gutenberg/wpml-config.xml

See https://onthegosystems.myjetbrains.com/youtrack/issue/comp-4101/

[comp-4101] Spectra: Updated advanced-heading block

---

elementor/wpml-config.xml

Also added another commit to move the config for "woocommerce-product-meta".
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-642/

[wpmlpb-642] Elementor: Add config for e-youtube widget (V4) 

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-371

[wpmlpb-371] Elementor: Set hotspot link type to url

---

elementor/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-639

[wpmlpb-639] Elementor: add config for share-buttons widget

---

woocommerce-multilingual/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-5053

[wcml-4802] Add support to the `_cogs_total_value` field

---

sitepress-multilingual-cms/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldev-5517

[wpmldev-5517] Add config for core Widget Group block

---

Divi/wpml-config.xml

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-689

[wpmlpb-689] Add support for media-url in block attributes
