OnTheGoSystems/wpml-config

divi/wpml-config.xml
Added these two custom fields to be copied
_et_pb_show_title
_et_pb_post_hide_nav
Refering this wpml support ticket https://wpml.org/forums/topic/translated-post-does-not-copy-page-settings-follow-up/
=> Added two custom fields

enfold/wpml-config.xml
@InoPlugs
we're setting `_aviaLayoutBuilderCleanData`  to ignore and creating it programmatically.
To achieve what you asking, so you can use the 'Duplicate' option. Or you can use WPML -> Translation Management -> Custom XML Configuration and override our online config file.
=> Revert "[Enfold] Update xlm config file"

enfold/wpml-config.xml
The upcoming Enfold release will have a new Avia Layout Builder element called 'Timeline'.
This is extending the WPML config file for that element.
=> Add new Avia Layout Builder Element 'Timeline' to WPML config file

avada/wpml-config.xml
Tested this also with current master and it doesn't break anything, meaning it's backwards compatible.
The rest of this fix will be included in WPML 4.0
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5227
=> Update wpml-config.xml for Avada in order to handle encoded content for the fusion_code tag

js_composer/wpml-config.xml
The code to make it work is in wpmlcore-5328
=> Add vc_safe encoding to attributes that use it.

config-index.xml
Dream Theme forked plugin The7 WPBakery Page Builder should use same config as WPBPB. Config for custom cells can be found in theme's config file.
=> Added The7 WPBakery Page Builder

cornerstone/wpml-config.xml
Cornerstone still uses shortcodes for the legacy blocks:
- x_image
- x_promo
- x_card
- x_creative_cta
- x_feature_box
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6208
=> Add support for media translation in Cornerstone

Divi/wpml-config.xml
This should fix https://github.com/OnTheGoSystems/wpml-config/pull/61 and a request from a client regarding the blurb module.
=> Adding link_option_url to text and blurb modules

cornerstone/wpml-config.xml
`ignore-content="1"` added to Classic Custom Headline and Classic Features Headline.
Removed repetitive names from `<shortcode-list>`
Some formatting has done.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmltm-3322
=> wpmltm-3322 Cornerstone classic custom headlines registered for translation twice

sitepress-multilingual-cms/wpml-config.xml
This is required for nested lists in order to have the strings in the
correct order when we have a mix of nested lists.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6613
=> Merge the 2 xpaths of the list block

elementor/wpml-config.xml
_elementor_css and _elementor_data have to be set to 'ignore' to avoid clients altering them.
=> Setting Elementor custom fields to ignore

beaver-builder/wpml-config.xml, config-index.xml, cornerstone/wpml-config.xml, elementor/wpml-config.xml
This is required because if the PB editor is disabled, we won't run all
the logic when the translation job is saved (and so the post meta wouldn't be
copied).
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6929
=> Copy post meta to flag the PB editor in Beaver Builder, Cornerstone and Elementor

Divi/wpml-config.xml, divi-builder/wpml-config.xml
Adding attributes for the et_pb_code shortcode in the /wpml-config/Divi/ and /wpml-config/divi-builder/ folders. Coming from this support ticket.
https://wpml.org/forums/topic/split-adding-a-new-divi-module-to-an-already-existing-page-becomes-a-mess-in-the-translation-editor/page/2/
=> Change to et_pb_code shortcode

woocommerce-multilingual/wpml-config.xml
We need to deploy this new configuration once we release the next WCML version from `develop` (supposedly with WPML 4.3.7). So let's wait before to merge in `master` so we don't block other updates.
https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-3083#focus=streamItem-102-390948.0-0
This has been reviewed already in https://git.onthegosystems.com/wpml/woocommerce-multilingual/blob/d630e68984eaf8493d7eea39e946e6a780bec467/wpml-config.xml.
=> Add WC blocks to WCML configuration

beaver-builder/wpml-config.xml, config-index.xml, cornerstone/wpml-config.xml, elementor/wpml-config.xml
This is required because if the PB editor is disabled, we won't run all
the logic when the translation job is saved (and so the post meta wouldn't be
copied).
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6929
=> Copy post meta to flag the PB editor in Beaver Builder, Cornerstone & Elementor

avada/wpml-config.xml
A number of elements in Avada can have dynamic content. I have examined all of them and added `dynamic_params` attribute to relevant shortcodes.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7156
=> Cannot translate dynamic fields in Avada 6.2.

config-index.xml
Fix Gutenberg Blocks – Ultimate Addons for Gutenberg plugin name
=> Fix plugin name

sitepress-multilingual-cms/wpml-config.xml
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7294
=> Add support for image block's title/alt when there's a link on the image

beaver-builder/wpml-config.xml
I am making use of the new API PB configuration structure defined in [wpmlcore-7241](https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-7241#focus=Comments-102-413345.0-0).
I tested this with the feature branch `api-pb-config` and it works like a charm.
Also, this configuration will be simply ignored for old WPML version that won't support this new structure.
The new modules are:
- Button Group
- List
- Login
- Search
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3492
=> Add support for new modules in Beaver Builder 2.4

custom-post-type-ui/wpml-config.xml
Made the option `cptui_taxonomies` translatable in the same way as `cptui_post_type` + Added the ability to translate the other labels of these custom types.
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3502
=> Update config for Custom Post Type UI

beaver-builder/wpml-config.xml
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3458
=> Make Beaver Builder's taxonomy `fl-builder-template-type` not translatable

config-index.xml, sensei/wpml-config.xml
This PR updates the config file for Sensei LMS to be the same as https://github.com/Automattic/sensei/pull/3840. In testing, our local version seemed to be overriding the hosted version, but thought it would be safest to make the same updates here.
This PR:
- Enables translating modules, questions and question categories.
- Enables translating user-defined values specified in settings.
It's not clear to me why `quiz`, `multiple_question` and `sensei_message` were previously set to translatable. Messages are sent between teachers and students, so those don't need to be translated, while `quiz` and `multiple_question` aren't directly accessible in WP admin.
=> Update config file for Sensei LMS

sitepress-multilingual-cms/wpml-config.xml
add //th xpath for core/table so table headers are translatable in the CTE and ATE
Related WPML ticket: https://wpml.org/forums/topic/i-am-not-able-to-find-that-string-for-translation/
=> Add xpath for core/table headers in sitepress-multilingual-cms 

Divi/wpml-config.xml
The _et_pb_old_content field shows in the translation editor as a line, but it needs to be a text area/wysiwyg.
It adds the style attribute to the field.
=> compsupp-5516 - changes the editor style for _et_pb_old_content

Divi/wpml-config.xml
Added attribute definitions for `et_pb_slide`:
- image_tablet
- image_phone
=> [DIVI] Add support for missing responsive image attributes for `et_pb_slide`

mailchimp-for-wp/wpml-config.xml
Added new custom field `_mc4wp_settings` to copy the setting only once.
https://onthegosystems.myjetbrains.com/youtrack/issue/mcml-8
=> Mailchimp - Set Mailchimp setting to copy once.

avada/wpml-config.xml
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5934
The fusion_builder_status is duplicated with two different settings. Removing the `ignore` one.
=> Set fusion_builder_status to copy-once

woocommerce-bookings/wpml-config.xml
These 2 CPTs are included in the main translation job (for `wc_booking`).
https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-3789
=> [WC Bookings] disable automatic for `bookable_person` and `bookable_resource`

avada/wpml-config.xml
As other "form" CPTs (e.g. CF7), we will disable Translate Everything for Avada Forms as we consider these contents are made of short strings without context for a relevant automatic translation.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldoc-1560#focus=Comments-102-494584.0-0
=> [Avada] Disable Translate Everything for Avada Forms

js_composer/wpml-config.xml
Allow user to translate iframe in `vc_gmaps` shortcode.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-9386
=> WPBakery - Translate the Google Maps widget

elementor/wpml-config.xml
Adding the additional information section title for `woocommerce-checkout-page`
=> Adding the additional information section title

config-index.xml
This is just a copy of the original WCML name.
https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-3908
=> Add index for the new WCML name "WooCommerce Multilingual & Multicurrency"

uncode-js_composer/wpml-config.xml
PS: I kept the "href" attribute there because I'm not sure if this is a typo or this attribute actually exists.
=> compsupp-6193 - Fixed issue with vc_button

woocommerce-mix-and-match-products/wpml-config.xml
Copy new meta fields that were added in MNM 2.0. Follow up to compat code: https://git.onthegosystems.com/glue-plugins/wpml/woocommerce-multilingual/-/merge_requests/1674
=> Update wpml-config.xml for Mix and Match 2

elementor/wpml-config.xml
- The Elementor Pro widget Archive product has an advanced section where nothing found message can be defined. 
- Reported on chat.
=> Add Support for Archive Product Nothing Found Message

avada/wpml-config.xml
With that change, the `fustion_post_cards` in the translated language will show in the translated post.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-245/
=> [wpmlpb-245] Support `fusion_post_cards` translation

Divi/wpml-config.xml, divi-builder/wpml-config.xml, extra/wpml-config.xml
We missed the "link" option in the "Team Member" module from Divi (and related Elegant Themes products)
=> Adding link_option_url attr to "team member"(DIVI)

elementor/wpml-config.xml
Translate Taxonomy filter widget strings, and loop grid strigns:
- Taxonomy filter: first_item_title("All")
- Loop grid, Pagination strings:
- Next
- Previous
- Load More
- No more posts custom message
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-394
=> [Elementor] Translate Taxonomy filter widget strings, and loop grid strings

elementor/wpml-config.xml
`Link>URL` is not working with repeater fields. We need `key_of` to make links translatable. (See wpmlpb-371)
Added `editor_type` attribute to description.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmltriage-645
=> Elementor - Fixed issue with Price List widget links.

kadence-blocks/wpml-config.xml
PostGrid/Carousel Block:
- "Read More" button is not translatable.
=> [Kadence blocks Pro] - Add support for PostGrid/Carousel Block

sitepress-multilingual-cms/wpml-config.xml
…ink` and `core/navigation-submenu`
=> [wpmlpb-346] Set link type for block attributes in `core/navigation-link` and `core/navigation-submenu`

config-index.xml
I've checked the plugins developed by Woo on [this page](https://woo.com/product-category/woocommerce-extensions/developed-by-woo/?categoryIds=3936&collections=product&page=1) and duplicated the ones for which we have an XML config.
=> [compdev-342] Duplicate configurations for the renamed Woo plugins

Divi/wpml-config.xml
- Allowing the heading from the **et_pb_slide** widget to support HTML tags: https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7107
=> Divi - Added support for et_pb_slide heading HTML tags

advanced-custom-fields/wpml-config.xml, config-index.xml
- Set the internal post type for CPTs and CTs as not translatable.
https://onthegosystems.myjetbrains.com/youtrack/issue/acfml-833/
=> [acfml-833] Config file for ACF.

Divi/wpml-config.xml
- Allowing the Hover from the et_pb_cta widget to support HTML tags: https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7220
=> Divi - Added support for et_pb_cta Hover HTML tags

Divi/wpml-config.xml, beaver-builder/wpml-config.xml, cornerstone/wpml-config.xml, elementor/wpml-config.xml, siteorigin/wpml-config.xml, sitepress-multilingual-cms/wpml-config.xml
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-419
=> Set labels for ATE Gen3

enfold/wpml-config.xml
- Allowing that images added as background in columns can be translated with Media Translation
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7248
=> Enfold - Enabling Media Translation for column background images

enfold/wpml-config.xml
Links in Fullscreen sliders are not translated when using automatic translation. This is because links are missing the encoding attribute in config.
See https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-11594
=> Enfold - Fixed links encoding in Fullscreen Slider widget.

config-index.xml
- Adding Spectra (old Ultimate Addons for Gutenberg) to config.index.ml file
- Modifying the plugin's name
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7376
=> Adding Spectra plugin to config.index.ml file

woocommerce-multilingual/wpml-config.xml
This configuration is based on WooCommerce version `9.0.1`.
https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-4742/
=> [wcml-4742] Add missing block configuration for WC Cart and WC Checkout

avada/wpml-config.xml
- Added support for translating images in "fusion_imageframe" widget
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7403/Avada-Switched-images-are-not-shown-on-the-translated-page-Fusion-builder
=> [Avada] - Added support for translating images in "fusion_imageframe" widget

elementor/wpml-config.xml
This will register the following strings from the new search widget(Elementor 2.23):
- Search input placeholder text.
- Search button text.
- No results text.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-520
=> [wpmlpb-520] Translate strings in Search widget

sitepress-multilingual-cms/wpml-config.xml
The refunds policy has incorrect markup on some headings:
```
<h2>heading2</h2>
```
This pull request will make sure the above works while [WooCommerce fixes the markup](https://github.com/woocommerce/woocommerce/issues/51618).
https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-4848
=> [wcml-4848] Temporary fix for incorrect blocks in WC's refunds policy page

config-index.xml, woocommerce-product-addons/wpml-config.xml
- The plugin name changed from "Add-ons" to "Add-Ons". I kept both versions for backward compatibility.
https://onthegosystems.myjetbrains.com/youtrack/issue/wcml-4857/WPML-4.7-Fix-WooCommerce-Product-Addons-integration
=> [wcml-4857] Update WooCommerce Product Addons plugin name

ultimate-addons-for-gutenberg/wpml-config.xml
- Adding support for Container links
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7603/Spectra-UAGB-Container-link-translation-not-working
=> [Spectra] Adding support for Container links

elementor/wpml-config.xml
See https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7621/Create-XML-config-for-Elementor-Floating-Elements
=> Updating Elementor XML - compsupp-7621

ultimate-addons-for-gutenberg/wpml-config.xml
- Info Box Block Title prefix was translatable only for <span> tags
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7655
=> [Spectra] Making Info Box Block Title prefix translatable for other HTML tags

elementor/wpml-config.xml
I've missed an issue when I reviewed https://github.com/OnTheGoSystems/wpml-config/pull/406.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6636
=> [Elementor Pro] Translate "price" field from Price list widget (fixup)

uncode/wpml-config.xml
Uncode has an option to add a link to vc_column and make it clickable. 
Youtrack: https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7679
=> [compsupp-7679] Uncode theme - Add translation to column links

uncode/wpml-config.xml
Transposed from https://github.com/OnTheGoSystems/wpml-config/pull/413 (squashed and reformatted the commit message).
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7678
=> [compsupp-7678] Uncode: Allow conversion of background images in Inner Column

sitepress-multilingual-cms/wpml-config.xml
Adding Media translation support for Gutenberg core/image widget
From: https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-12412
=> Gutenberg - Gallery block lightbox image is not replaced

cornerstone/wpml-config.xml
- Headline widgets: Adding support for translating Subheadlines
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-582/Cornestone-Subheadlines-are-not-translatable
=> [Cornestone] Adding support for translating Subheadlines

beaver-builder/wpml-config.xml
Beaver Builder Plugin 2.9 is adding new Gutenberg blocks, this new XML update will make them translatable with WPML.
Please refer to : https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7854
=> compsupp-7854  - Translate Gutenberg Blocks from Beaver Builder 2.9

Divi/wpml-config.xml
Somehow only the "Title (hover) allowed HTML. Adding HTML support for all titles attributes.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7907
=> [compsupp-7907] - Allow HTML tags in  CTA Title

woocommerce-bookings/wpml-config.xml
Besides the field value, WooCommerce Bookings stores the available slots for bookings in specific transients. Those transienmts get cleared when a booking product is edited, but we still need to clear the transients for the product translations.
This should get merged when WCML 5.4.0 gets released - there, we will include the logic to clear translations transients.
=> [wcml-4918] Copy the field storing the booking buffer period.

beaver-builder/wpml-config.xml
We are now handling it with a compatibility class (because of the data shape).
See wpmlpb-348.
=> [wpmlpb-570] Beaver Builder: Removing the pricing table widget

pro/wpml-config.xml
Improving support for Cornerstone button widget
The Secondary Button Text `anchor_text_secondary_content` is not translatable.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7950
PS: I checked the [cornerstone remote XML](https://github.com/OnTheGoSystems/wpml-config/blob/d1bb06915a0ab9a962405f947bc5bc24ce531a6c/cornerstone/wpml-config.xml#L255) already and it's up-to-date.
=> [compsupp-7950] Cornerstone Button > Secondary button text not translatable

elementor/wpml-config.xml
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-624/Elementor-Disambiguate-url-in-media-carousel-widget
=> [wpmlpb-624] Adjust the editor_type to link

Divi/wpml-config.xml
Add the attribute encoding="allow-html-tags" to prevent apostrophes and ampersands from being wrongly translated into HTML entities.
=> wpmlpb-651 - Add encoding to prevent incorrect HTML entity translation

seo-by-rank-math/wpml-config.xml
For both posts and products.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlwpseo-226/Rank-Math-Product-and-Posts-primary-categories-are-not-syncd-to-translations
=> [wpmlwpseo-226] RankMathSEO: Sync primary category to translations

elementor/wpml-config.xml
It supports the new widgets added in Elementor 3.29 as alpha features.
See also https://onthegosystems.myjetbrains.com/youtrack/issue/comp-4057/.
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-642/
=> [wpmlpb-642] Elementor: Add preliminary configuration for Editor v4

sitepress-multilingual-cms/wpml-config.xml
Making the WP Post Query Block's "Read more" text translatable.
From: https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-12759
=> wpmlsupp-12759 | Adding the WP Post Query Block's "Read more" text

Divi/wpml-config.xml
We already had a generic configuration, but I updated it to include other common fields.
This fixed the issue related to the blurb block.
Ref: https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3831
=> [comp-3831] Update generic config for blocks in Divi namespace

uncode/wpml-config.xml
Allowing HTML tags on the heading and subheading attributes from the `vc_custom_heading` widget.
From: [https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-12973](https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-12973)
=> [wpmlsupp-12973] Uncode - Allowing HTML tags in heading widget

Divi/wpml-config.xml
Closes #467 
https://github.com/OnTheGoSystems/wpml-config/issues/467
=> #467 Divi - add missing link field for the icon widget

ultimate-addons-for-gutenberg/wpml-config.xml
Spectra - Ultimate Addons for Gutenberg
Make the Image caption translatable in ATE for the "Image with caption (Spectra)" block.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-8089
=> Image Caption is not translatable

js_composer/wpml-config.xml
WPBakery stores grid shortcode data in the post‑meta `_vc_post_settings`
```
array (
0 => 
array (
'vc_grid_id' => 
array (
'shortcodes' => 
array (
'1752692542765-444b9747-baac-1' => 
array (
'tag' => 'vc_media_grid',
'atts' => 
array (
'css' => '',
'initial_loading_animation' => 'none',
'grid_id' => 'vc_gid:1752692542765-444b9747-baac-1',
'include' => '95758,95757,95756',
),
'content' => '',
),
),
),
),
)
```
Since the translation preference of this fields was set as "ignore", translations won’t have it.
Coming from: https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlsupp-12987
=> Missing vc_media_grid in translations - wpmlsupp-12987

Divi/wpml-config.xml
Adding the Product ID's translation in the Namespace. This shouldn't affect other blocks as it is exclusive for products.
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-4205/Divi-5-First-batch-of-WooCommerce-Modules
=> [Divi 5] Adding Product ID's translation in the Namespace

avada/wpml-config.xml
Avada Title widget’s link field doesn't auto-translate internal links. Links on the translated page still point to the default language URL.
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-8149
=> [compsupp-8149] Avada Title widget links not updated on translations
